var ITEM_COUNTS = 143;//默认显示143小方格
var ORDER_FIRST = 1;
var ORDER_SECOND = 2;
var ORDER_THREE = 3;//第三轮 董事长加抽
var GROUP_COMPANY = 1;
var GROUP_DIRECTOR = 3;
var GROUP_CONSTRUCTION = 2;
var GROUP_PERSONS = 4;
var GROUP_ALL = 5;//全员组
var SECOND_AWARDS_FIRST = 7;//一等奖
var SECOND_AWARDS_SECOND = 8;//二等奖
var SECOND_AWARDS_THREE = 9;//三等奖
var SECOND_AWARDS_FOURTH = 10;//特别奖
var AWARDS_FIRST = 1;
var AWARDS_SECOND = 2;
var AWARDS_THREE = 3;
var AWARDS_SPECIAL = 0;
var AWARDS_ESPECIAL = 6;//特别奖
var AWARDS_COMMON = 4;
var AWARDS_COMMON_NO_YEAR = 5;
var ARRAY_AWARDS = ["特等奖","一等奖","二等奖","三等奖","阳光普照","阳光普照(未满一年)","特别奖"];
var ORDER_SECOND_SPECIAL_ARRAY_AWARDS = [" "," "," "," "," "," "," ","一等奖","二等奖","三等奖","董事长特别奖"];
var CURRENT_AWARD_INDEX = 3;//当前设置的奖项。默认三等奖
var CURRENT_GROUP_INDEX = 1;//默认为公司组
var CURRENT_ORDER_INDEX = 1;//默认为第一轮

var TEST_ENABLE = false;
var TEST_LUCKEY_ARRAY = new Array();
